# **Connecting to the google drive**

In [209]:
# File is stored in the drive so we link the drive to access the file 
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# **Importing the libraries**

In [210]:
# We import the required modules for machine learning, like numpy, pandas and matplotlib 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# **Importing the dataset for regression**

In [211]:
# we import the data using pandas module and import the 3rd and 4th column into x and y respectively
data1 = pd.read_csv('/content/drive/MyDrive/classification and regression/Data_regression.csv')
x1=data1.iloc[:,:-1].values
y1=data1.iloc[:,-1].values
print(data1)
print("----------------------------------------------------------------------")
print(x1)
print("----------------------------------------------------------------------")
print(y1)

         AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]
----------------------------------------------------------------------
[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
----------------------------------------------------------------------
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


# **Importing the dataset for Classification**

In [212]:
# we import the data using pandas module and import the 3rd and 4th column into x and y respectively
data2 = pd.read_csv('/content/drive/MyDrive/classification and regression/Data_classification copy.csv')
x2=data2.iloc[:,:-1].values
y2=data2.iloc[:,-1].values
print(data2)
print("----------------------------------------------------------------------")
print(x2)
print("----------------------------------------------------------------------")
print(y2)

     Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
678              776715                3                        1   
679              841769                2                        1   
680              888820                5                       10   
681              897471                4                        8   
682              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2   
1        

# **Splitting the data into train and test sets for regression**

In [213]:
from sklearn.model_selection import train_test_split
x_train_reg, x_test_reg, y_train_reg, y_test_reg= train_test_split(x1, y1, test_size =0.2, random_state=0)
print(x_train_reg)
print("------------------------------")
print(y_train_reg)
print("------------------------------")
print(x_test_reg)
print("------------------------------")
print(y_test_reg)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]
------------------------------
[473.93 467.87 431.97 ... 459.01 462.72 428.12]
------------------------------
[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]
------------------------------
[431.23 460.01 461.14 ... 473.26 438.   463.28]


# **Splitting the data into train and test sets for Classification**

In [214]:
from sklearn.model_selection import train_test_split
x_train_class, x_test_class, y_train_class, y_test_class= train_test_split(x2, y2, test_size =0.2, random_state=0)
print(x_train_class)
print("------------------------------")
print(y_train_class)
print("------------------------------")
print(x_test_class)
print("------------------------------")
print(y_test_class)

[[ 752904      10       1 ...       5       4       1]
 [1218860       1       1 ...       3       1       1]
 [ 411453       5       1 ...       3       1       1]
 ...
 [1214092       1       1 ...       1       1       1]
 [1303489       3       1 ...       2       1       1]
 [ 378275      10       9 ...       7       7       1]]
------------------------------
[4 2 2 2 4 2 2 2 2 4 2 4 2 4 4 2 2 2 2 4 4 2 4 4 4 4 4 4 2 2 2 2 2 2 4 4 4
 2 2 2 4 2 2 4 4 2 4 2 2 4 4 2 2 2 2 2 2 2 2 2 2 4 2 2 2 2 2 4 4 2 4 2 2 2
 4 2 2 2 2 4 4 2 2 4 4 2 2 4 4 2 4 2 4 4 2 2 2 4 2 4 2 4 2 2 2 2 2 4 2 2 4
 2 2 4 2 2 2 2 2 4 2 2 4 2 4 2 2 4 4 4 2 2 2 2 2 2 4 4 2 2 2 2 2 2 2 4 2 2
 4 2 2 2 2 2 2 2 4 2 2 2 4 4 2 4 2 2 2 4 2 2 2 4 4 2 4 2 2 4 2 2 2 2 2 2 2
 4 4 4 4 2 4 2 4 2 4 4 4 2 2 4 2 2 2 2 4 4 2 2 2 4 2 2 4 2 2 2 2 4 4 2 2 2
 2 2 2 2 2 2 2 2 4 2 4 2 2 2 2 2 2 4 4 4 4 2 2 4 2 4 2 4 2 2 2 2 4 2 4 2 2
 2 2 4 2 2 4 2 2 2 2 2 2 2 4 2 4 2 2 2 4 2 2 2 2 2 4 2 2 2 2 4 2 2 4 2 2 2
 2 4 4 2 2 2 2 4 2 2 4 2 2 2 2 4 

# **Feature Scaling for regression**

In [215]:
from sklearn.preprocessing import StandardScaler 
sc= StandardScaler()
x_train_reg=sc.fit_transform(x_train_reg)
x_test_reg=sc.transform(x_test_reg)
print(x_train_reg)
print("--------------------")
print(x_test_reg)

[[-1.136 -0.887  0.674  0.521]
 [-0.806 -0.01   0.451  0.145]
 [ 1.771  1.847  0.243 -1.884]
 ...
 [-0.384 -1.249  0.845  0.131]
 [-0.923 -1.042  1.547  0.883]
 [ 1.701  1.058 -1.204 -2.423]]
--------------------
[[ 1.209  1.847 -0.619 -0.29 ]
 [-0.294 -0.395  1.392  0.769]
 [-0.646 -0.886  1.005  1.77 ]
 ...
 [-0.999 -0.746  1.767  1.021]
 [ 1.024 -0.51  -1.645 -0.964]
 [-0.321 -1.133 -1.034  0.065]]


# **Feature Scaling for Classification**

In [216]:
from sklearn.preprocessing import StandardScaler 
sc= StandardScaler()
x_train_class=sc.fit_transform(x_train_class)
x_test_class=sc.transform(x_test_class)
print(x_train_class)
print("--------------------")
print(x_test_class)


[[-0.498  1.988 -0.698 ...  0.619  0.345 -0.339]
 [ 0.192 -1.225 -0.698 ... -0.189 -0.622 -0.339]
 [-1.005  0.203 -0.698 ... -0.189 -0.622 -0.339]
 ...
 [ 0.185 -1.225 -0.698 ... -0.996 -0.622 -0.339]
 [ 0.318 -0.511 -0.698 ... -0.592 -0.622 -0.339]
 [-1.054  1.988  1.905 ...  1.427  1.312 -0.339]]
--------------------
[[ 0.125 -1.225 -0.698 ... -0.996 -0.622 -0.339]
 [ 0.099 -0.511 -0.698 ... -0.592 -0.622 -0.339]
 [-0.567  0.203  0.604 ...  0.215  0.023 -0.339]
 ...
 [-1.067 -0.154 -0.698 ... -0.996 -0.622 -0.339]
 [ 0.332 -0.154  2.23  ...  2.234  2.279 -0.339]
 [ 0.07  -0.868 -0.698 ... -0.592 -0.622 -0.339]]


# **----------------------REGRESSION MODELS IMPLEMENTATION--------------------**

#**Training the Simple Regression model on the training set**

In [217]:
from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor.fit(x_train_reg,y_train_reg)

LinearRegression()

# **Predicting the Results on test set (Simple Regression)**

In [218]:
# we use the predict method to generate the y_pred values and we reshape the matrix to print column wise
y_pred_SR= regressor.predict(x_test_reg)
print(y_pred_SR)

[431.428 458.561 462.753 ... 469.518 442.418 461.883]


# **Calculating the r^2 score (Simple Regression)**

In [219]:
from sklearn.metrics import r2_score
r2_SR = r2_score(y_test_reg,y_pred_SR)
print(r2_SR)

0.9325315554761302


#**Training the Multi Linear Regression model on the training set**

In [220]:
from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor.fit(x_train_reg,y_train_reg)

LinearRegression()

# **Predicting the Results on test set (Multi Linear Regression)**

In [221]:
# we use the predict method to generate the y_pred values and we reshape the matrix to print column wise
y_pred_MLR = regressor.predict (x_test_reg)
np.set_printoptions (precision=3)
print (np. concatenate ( (y_pred_MLR. reshape (len (y_pred_MLR), 1), y_test_reg. reshape (len(y_test_reg) , 1)) , 1))



[[431.428 431.23 ]
 [458.561 460.01 ]
 [462.753 461.14 ]
 ...
 [469.518 473.26 ]
 [442.418 438.   ]
 [461.883 463.28 ]]


# **Calculating the r^2 score (Multi Linear Regression)**

In [222]:
from sklearn.metrics import r2_score
r2_MLR = r2_score(y_test_reg,y_pred_SR)
print(r2_MLR)

0.9325315554761302


#**Training the Polynomial Regression model on the training set**

In [223]:
# we use the train set to train the polynomial regression model but be fore that we need to do a bit of preprocessing 
# we need to the values with a power in a matrix
from sklearn.preprocessing import PolynomialFeatures
polyreg=PolynomialFeatures(degree=4)
x_train_PR=polyreg.fit_transform(x_train_reg)
model = LinearRegression()
model.fit(x_train_PR, y_train_reg)

LinearRegression()

# **Predicting the Results on test set (Polynomial Regression)**

In [224]:
# we use the predict method to generate the y_pred values and we reshape the matrix to print column wise
y_pred_PR = regressor.predict (x_test_reg)
np.set_printoptions (precision=3)
print (np. concatenate ( (y_pred_PR. reshape (len (y_pred_PR), 1), y_test_reg. reshape (len(y_test_reg) , 1)) , 1))

[[431.428 431.23 ]
 [458.561 460.01 ]
 [462.753 461.14 ]
 ...
 [469.518 473.26 ]
 [442.418 438.   ]
 [461.883 463.28 ]]


# **Calculating the r^2 score (Polynomial Regression)**

In [225]:
from sklearn.metrics import r2_score
r2_PR = r2_score(y_test_reg,y_pred_PR)
print(r2_PR)

0.9325315554761302


#**Training the Decision Tree Regression model on the training set**

In [226]:
# Fitting Random Forest Regression to the dataset
# import the regressor
from sklearn.tree import DecisionTreeRegressor
 
 # create regressor object
regressor_DTR = DecisionTreeRegressor( random_state = 0)
 
# fit the regressor with x and y data
regressor_DTR.fit(x_train_reg, y_train_reg) 

DecisionTreeRegressor(random_state=0)

# **Predicting the Results on test set (Decision Tree Regression)**

In [227]:
# we use the predict method to generate the y_pred values and we reshape the matrix to print column wise
y_pred_DTR = regressor_DTR.predict(x_test_reg) # test the output by changing values
print(y_pred_DTR)



[431.28 459.59 460.06 ... 471.46 437.76 462.74]


# **Calculating the r^2 score (Decision Tree Regression)**

In [228]:
from sklearn.metrics import r2_score
r2_DTR = r2_score(y_test_reg,y_pred_DTR)
print(r2_DTR)

0.9231106384743017


#**Training the Random Forest Regression model on the training set**

In [229]:
# Fitting Random Forest Regression to the dataset
# import the regressor
from sklearn.ensemble import RandomForestRegressor
 
 # create regressor object
regressor_RFR = RandomForestRegressor(n_estimators = 100, random_state = 0)
 
# fit the regressor with x and y data
regressor_RFR.fit(x_train_reg, y_train_reg) 

RandomForestRegressor(random_state=0)

# **Predicting the Results on test set (Random Forest Regression)**

In [230]:
# we use the predict method to generate the y_pred values and we reshape the matrix to print column wise
y_pred_RFR = regressor_RFR.predict(x_test_reg) # test the output by changing values
print(y_pred_RFR)



[433.677 457.711 463.411 ... 468.968 439.167 461.288]


# **Calculating the r^2 score (Random Forest Regression)**

In [231]:
from sklearn.metrics import r2_score
r2_RFR = r2_score(y_test_reg,y_pred_RFR)
print(r2_RFR)

0.9650994584080381


#**Training the Support Vector Regression model on the training set**

In [232]:
# import the model
from sklearn.svm import SVR
# create the model object
regressor_SVR = SVR()
# fit the model on the data
regressor_SVR.fit(x_train_reg, y_train_reg) 

SVR()

# **Predicting the Results on test set (Support Vector Regression)**

In [233]:
# we use the predict method to generate the y_pred values and we reshape the matrix to print column wise
y_pred_SVR = regressor_SVR.predict(x_test_reg) # test the output by changing values
print(y_pred_SVR)



[433.689 457.272 461.811 ... 470.291 439.517 461.243]


# **Calculating the r^2 score (Support Vector Regression)**

In [234]:
from sklearn.metrics import r2_score
r2_SVR = r2_score(y_test_reg,y_pred_SVR)
print(r2_SVR)

0.9430195908033736


# **------------------CLASSIFICATION MODELS IMPLEMENTATION--------------------**

#**Training the Logistic Regression model on the training set**

In [235]:
from sklearn.linear_model import LogisticRegression
regressor_LR=LogisticRegression()
regressor_LR.fit(x_train_class,y_train_class)

LogisticRegression()

# **Predicting the Results on test set (Logistic Regression)**

In [236]:
# we use the predict method to generate the y_pred values and we reshape the matrix to print column wise
y_pred_LR = regressor_LR.predict(x_test_class) # test the output by changing values
print(y_pred_LR)



[2 2 4 4 2 2 2 4 2 2 4 2 4 2 2 2 4 4 4 2 2 2 4 2 4 4 2 2 2 4 2 4 4 2 2 2 4
 4 2 4 2 2 2 2 2 2 2 4 2 2 4 2 4 2 2 2 4 4 2 4 2 2 2 2 2 2 2 2 4 4 2 2 2 2
 2 2 4 2 2 2 4 2 4 2 2 4 2 4 4 2 4 2 4 4 2 4 4 4 4 2 2 2 4 4 2 2 4 2 2 2 4
 2 2 4 2 2 2 2 2 2 2 4 2 2 4 4 2 4 2 4 2 2 4 2 2 4 2]


# **Making the confusion matrix(Logistic Regression)**

In [237]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_LR = confusion_matrix(y_test_class,y_pred_LR)
print(cm_LR)
accuracy_score(y_test_class,y_pred_LR)

[[84  3]
 [ 3 47]]


0.9562043795620438

#**Training the KNN classification model on the training set**

In [238]:
from sklearn.neighbors import KNeighborsClassifier
KNN_classifier=KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)
KNN_classifier.fit(x_train_class,y_train_class)

KNeighborsClassifier()

# **Predicting the Results on test set(KNN)**



In [239]:
y_pred_KNN=KNN_classifier.predict(x_test_class)
print(np.concatenate((y_pred_KNN.reshape(len(y_pred_KNN),1),y_test_class.reshape(len(y_test_class),1)),1))

[[2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]]


# **Making the confusion matrix(KNN)**

In [240]:
from sklearn.metrics import confusion_matrix, accuracy_score,ConfusionMatrixDisplay
cm_KNN = confusion_matrix(y_test_class,y_pred_KNN)
print(cm_KNN)
accuracy_score(y_test_class,y_pred_KNN)

[[83  4]
 [ 2 48]]


0.9562043795620438

# **Visualizing confusion matrix**

#**Training the Navie Bayes model on the training set**

In [241]:
from sklearn.naive_bayes import GaussianNB
NB_classifier=GaussianNB()
NB_classifier.fit(x_train_class,y_train_class)

GaussianNB()

# **Predicting the Results on test set (Navie Bayes)**



In [242]:
y_pred_NB=NB_classifier.predict(x_test_class)
print(np.concatenate((y_pred_NB.reshape(len(y_pred_NB),1),y_test_class.reshape(len(y_test_class),1)),1))

[[2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]]


# **Making the confusion matrix (Navie Bayes)**

---



In [243]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_NB = confusion_matrix(y_test_class,y_pred_NB)
print(cm_NB)
accuracy_score(y_test_class,y_pred_NB)

[[80  7]
 [ 0 50]]


0.948905109489051

#**Training the SVM model on the training set**

In [244]:
from sklearn.svm import SVC
SVM_classifier=SVC(kernel='rbf',random_state=0)
SVM_classifier.fit(x_train_class,y_train_class)

SVC(random_state=0)

# **Predicting the Results on test set (Support Vector Machine)**



In [245]:
y_pred_SVM=SVM_classifier.predict(x_test_class)
print(np.concatenate((y_pred_SVM.reshape(len(y_pred_SVM),1),y_test_class.reshape(len(y_test_class),1)),1))

[[2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 4]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]]


# **Making the confusion matrix (Support Vector Machine)**

In [246]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_SVM = confusion_matrix(y_test_class,y_pred_SVM)
print(cm_SVM)
accuracy_score(y_test_class,y_pred_SVM)

[[82  5]
 [ 1 49]]


0.9562043795620438

#**Training the kernel SVM model on the training set**

In [247]:
from sklearn.svm import SVC
SVM_classifier=SVC(kernel='linear',random_state=0)
SVM_classifier.fit(x_train_class,y_train_class)

SVC(kernel='linear', random_state=0)

# **Predicting the Results on test set (Kernel Support Vector Machine)**



In [248]:
y_pred_SVM=SVM_classifier.predict(x_test_class)
print(np.concatenate((y_pred_SVM.reshape(len(y_pred_SVM),1),y_test_class.reshape(len(y_test_class),1)),1))

[[2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 4]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]]


# **Making the confusion matrix (Kernel Support Vector Machine)**

In [249]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_SVM = confusion_matrix(y_test_class,y_pred_SVM)
print(cm_SVM)
accuracy_score(y_test_class,y_pred_SVM)

[[83  4]
 [ 2 48]]


0.9562043795620438

#**Training the Random forest model on the training set**

In [250]:
from sklearn.ensemble import RandomForestClassifier
RF_classifier=RandomForestClassifier(n_estimators=10,criterion="entropy",random_state=0)
RF_classifier.fit(x_train_class,y_train_class)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

# **Predicting the Results on test set (Random Forest)**



In [251]:
y_pred_RF=RF_classifier.predict(x_test_class)
print(np.concatenate((y_pred_RF.reshape(len(y_pred_RF),1),y_test_class.reshape(len(y_test_class),1)),1))

[[2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 4]
 [4 4]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]]


# **Making the confusion matrix (Random Forest)**

In [252]:
from sklearn.metrics import confusion_matrix, accuracy_score
RF_cm = confusion_matrix(y_test_class,y_pred_RF)
print(RF_cm)
accuracy_score(y_test_class,y_pred_RF)

[[84  3]
 [ 3 47]]


0.9562043795620438

#**Training the Decision tree model on the training set**

In [253]:
from sklearn.tree import DecisionTreeClassifier
DTM_classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
DTM_classifier.fit(x_train_class,y_train_class)

DecisionTreeClassifier(criterion='entropy', random_state=0)

# **Predicting the Results on test set (DECISION TREE)**



In [254]:
y_pred_DTM=DTM_classifier.predict(x_test_class)
print(np.concatenate((y_pred_DTM.reshape(len(y_pred_DTM),1),y_test_class.reshape(len(y_test_class),1)),1))

[[2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 4]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]]


# **Making the confusion matrix (DECISION TREE)**

In [255]:
from sklearn.metrics import confusion_matrix, accuracy_score
DTM_cm = confusion_matrix(y_test_class,y_pred_DTM)
print(DTM_cm)
accuracy_score(y_test_class,y_pred_DTM)

[[85  2]
 [ 2 48]]


0.9708029197080292