# **Connecting to the google drive**

In [46]:
# File is stored in the drive so we link the drive to access the file 
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# **Importing the libraries**

In [47]:
# We import the required modules for machine learning, like numpy, pandas and matplotlib 
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.12.0'

# **Importing the dataset (Data Preprocessing)**

In [48]:
# we import the data using pandas module and import the 3rd and 4th column into x and y respectively
data = pd.read_csv('/content/drive/MyDrive/ANN/Churn_Modelling.csv')
x=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values
print(x)
print("----------------------------------------------------------------------")
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
----------------------------------------------------------------------
[1 0 1 ... 1 1 0]


# **Encoding the Categorical Data (Data Processing)**

*lable encoding in the GENDER Column*

In [49]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


*Using One Hot Encoder encoding the COUNTRY column*

In [50]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# **Splitting the data into Training and test (Data Procsessing)**

In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size =0.2, random_state=0)
print(x_train)
print("------------------------------")
print(y_train)
print("------------------------------")
print(x_test)
print("------------------------------")
print(y_test)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]
------------------------------
[0 0 0 ... 0 0 1]
------------------------------
[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]
------------------------------
[0 1 0 ... 0 0 0]


# **Feature Scaling**

In [52]:
from sklearn.preprocessing import StandardScaler 
sc= StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train)
print("--------------------")
print(x_test)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]
--------------------
[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


#**Initializing the ANN Model**

In [53]:
ann=tf.keras.models.Sequential()

*Adding the input layer and the first hidden layer*

In [54]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

*Adding the second hidden*

In [55]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

*Adding the output layer*

In [56]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# **Training the ANN**

In [57]:
ann.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

In [58]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 4ms/step - loss: 0.6647 - accuracy: 0.6491
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5314 - accuracy: 0.7959
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4848 - accuracy: 0.7971
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4524 - accuracy: 0.8044
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4349 - accuracy: 0.8089
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4206 - accuracy: 0.8154
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4050 - accuracy: 0.8217
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3907 - accuracy: 0.8313
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3814 - accuracy: 0.8345
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3748 - accura

In [60]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 125ms/step
[[False]]


# **Predicting the test results**

In [61]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# **Making the confusion matrix**

---



In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1527   68]
 [ 212  193]]


0.86